// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt9lZvuX-e26AZwgPRgf8XhLI5k_Bz9DQ',
    appId: '1:3627353309:android:18b486ff51fe432ed30734',
    messagingSenderId: '3627353309',
    projectId: 'divertissement-9c481',
    storageBucket: 'divertissement-9c481.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPcmT5EVkmO6nrP1TWQUAAUgvu0SoE18I',
    appId: '1:3627353309:ios:3a86662c72bba00ed30734',
    messagingSenderId: '3627353309',
    projectId: 'divertissement-9c481',
    storageBucket: 'divertissement-9c481.appspot.com',
    androidClientId: '3627353309-65sh6vmteh9gj1msk3n493frilcj84uv.apps.googleusercontent.com',
    iosClientId: '3627353309-49qtkhbg4s6pejnoh3pqfmu2o1eo9smo.apps.googleusercontent.com',
    iosBundleId: 'com.example.evenemento',
  );
}
